### ISSUE TITLE
No options on the menu

### ISSUE THREAD

**Issue by bautifonta436** [zephyrj/engine-crane#10]
When I open the app, it doesnt' show me anything but a white scren. Here is the log
[engine_crane.log](https://github.com/zephyrj/engine-crane/files/10100211/engine_crane.log)

**Comment by zephyrj** [comment]
I'm looking into this issue at the moment. I'm not able to reproduce the problem at the moment.

What directory are you running engine-crane in? Could it be a directory that can't be written to?
Are you using Windows 10 or Window 11?

**Comment by bautifonta436** [comment]
It was a problem of the pc. I just had to restart the pc and everything worked properly, thanks.

**Comment by zephyrj** [comment]
Excellent, glad it's working
