### ISSUE TITLE
No config file?

### ISSUE THREAD

**Issue by SzaZoa1227** [zephyrj/engine-crane#13]
I have attached the log file
[engine_crane.log](https://github.com/zephyrj/engine-crane/files/10231256/engine_crane.log)

**Comment by zephyrj** [comment]
Hi, thanks for the feedback. Sorry for not replying to this sooner - I've been away over Christmas and New Year.

Normally the program should start up normally even without this file; is it not opening a window for you? 

A couple of things that may help me identify your issue:
- where are you running engine-crane from?
- what is your Assetto Corsa directory?

**Comment by zephyrj** [comment]
I'm assuming this was the app opening and then immediately closing - with only the config message appearing in the log file. If this is the case then this has been resolved in the latest version:
https://github.com/zephyrj/engine-crane/releases/tag/v0.1.16-alpha
