### ISSUE TITLE
engine crane file issue

### ISSUE THREAD

**Issue by Leonp98** [zephyrj/engine-crane#6]
Assetto file selected but says no cars found

**Comment by zephyrj** [comment]
Which folder are you selecting? You should pick your top level Assetto Corsa install path so as an example:
`C:\Program Files (x86)\Steam\steamapps\common\assettocorsa`

I've never used a custom library but I would expect that path would end up being:
`<library_path>\steamapps\common\assettocorsa`
*replace <library_path> with your Steam library path.

Do not select the content or cars directories - it must be the path to the assetto corsa install folder

**Comment by zephyrj** [comment]
If this doesn't resolve your issue then would you please send me the log file that gets generated by engine-crane when you run it? It will be called `engine_crane.log` - I can then have a look through it and see what else the issue could be

**Comment by zephyrj** [comment]
Hi, did you manage to resolve your issue?

**Comment by Leonp98** [comment]
Hi sorry i haven’t replied the problem was my file location its working fine now thanks alot

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by zephyrj** [comment]
No worries - glad you've got it working. Hope you have fun with it
