### ISSUE TITLE
Automation Engines to Assetto Corsa

### ISSUE THREAD

**Issue by DaNyde23** [zephyrj/engine-crane#7]
When i launch the Content Manager, the name of the car and my engine does appear, but there are no actual changes to the engine and everything stays the same. I've tried restarting my pc but it didn't make any difference. Any help? Should i use any specific Automation-cars like another user requested? If yes, which ones?

**Comment by zephyrj** [comment]
Hi,

The aim is for this to work with all the cars if possible - which Assetto Corsa car are you seeing the problem on? If you could attach the engine_crane.log file that will exist in the same directory as the engine-crane executable then I can have a look through and try to work out why it isn't working

**Comment by DaNyde23** [comment]
The issue exists on every AC car, i think the problem lies on Automation, i have switched the Automation version from the current, to an older one and now it works. However i like the newest version better. Is engine crane already developed for the newest version of Automation?

**Comment by zephyrj** [comment]
I've just done a test just now and it seems to be working in my setup.

> engine-crane version: [v0.1.9-alpha](https://github.com/zephyrj/engine-crane/releases/tag/v0.1.9-alpha)
> Automation version: LCV 4.2.32 (released 30th October)
> AC car: BMW M1

I verified that the engine.ini and power.lut files were being updated.

Are you using the most recent version of engine-crane? The latest version is available at:
https://github.com/zephyrj/engine-crane/releases/tag/v0.1.9-alpha
You can also try the steps I've listed here to see if they help you: https://sykology.dev/fixing-problems/

If you're still having issues can you please send me the engine_crane.log file that will be present inside the same directory that engine-crane is in? I can use this to help diagnose the issue

**Comment by zephyrj** [comment]
You can send it over here - all you have to do is drag and drop the file into the "Write" box you use to type replies

**Comment by DaNyde23** [comment]
I think i found the problem, when the AI is on the last step, it updates everything to "\Users\reune\AppData\Local\BeamNG.drive\0.26\mods\grt5" however thats the wrong path, it should be:
"\Users\David\AppData\Local\BeamNG.drive\0.26\mods\grt5"

**Comment by zephyrj** [comment]
Cool. I'm looking at getting it to save the last set value for both the AC and BeamNG mod path for the next update I make to the tool; that should help in your case

**Comment by DaNyde23** [comment]
Thanks a lot, definitely worth a follow on youtube!

**Comment by zephyrj** [comment]
> Is there a way I can set "\Users\David\AppData\Local\BeamNG.drive\0.26\mods" as the default path for ever? Because everytime i open engine crane the wrong path is already selected by default.

https://github.com/zephyrj/engine-crane/releases/tag/v0.1.11-alpha this release should automatically save the paths that you set and they should be loaded up every time you start it

**Comment by DaNyde23** [comment]
> 

Cool, do engine sounds get transfered now too, if not, when?

**Comment by DaNyde23** [comment]
Oh and do swaps work with mods too?

**Comment by zephyrj** [comment]
> > 
> 
> Cool, do engine sounds get transfered now too, if not, when?

No, having checked over on the Automation discord the engine noises can't be transferred over directly due to licenses. I will need to investigate other options for this so I don't have a timeline

**Comment by zephyrj** [comment]
> Oh and do swaps work with mods too?

It should work with any car that doesn't have an encrypted set of data files; some mods do encrypt them so those will not work.
